version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: akatsuki-postgres
    restart: always
    environment:
      POSTGRES_DB: chidori
      POSTGRES_USER: chidori
      POSTGRES_PASSWORD: chidori
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: